### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zhuangside** [caozx1110/Carbon#1]
嗨，老兄，直接运行dist里的carbonui.exe报错，错误信息如下：
Traceback (most recent call last):
  File "CarbonUI.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "MainProgress.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "WakeUp.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "Carbon.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "WeChat.py", line 82, in <module>
  File "WeChat.py", line 83, in WeChat
  File "PersonalComputer.py", line 23, in __init__
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\q7423\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\APP'

**Comment by caozx1110** [comment]
直接运行肯定会报错（doge）
应该当时为了指定所有的软件路径，建立了一个文件夹储存快捷方式
并且百度云语音识别服务也到期了
讯飞的唤醒服务也到期了
所以这个repo就是给大家参考参考当年暑假心血来潮搞的小玩具




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月04日 18:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [caozx1110/Carbon] 报错 (Issue #1) |

嗨，老兄，直接运行dist里的carbonui.exe报错，错误信息如下：
Traceback (most recent call last):
File "CarbonUI.py", line 15, in
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "MainProgress.py", line 9, in
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "WakeUp.py", line 14, in
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "Carbon.py", line 21, in
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "WeChat.py", line 82, in
File "WeChat.py", line 83, in WeChat
File "PersonalComputer.py", line 23, in init
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\Users\q7423\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\APP'

**Comment by zhuangside** [comment]
好的，多谢老兄的及时回复，我只了解python的语法但我想试着做一个，想问一下相关的学习资料(例如书籍，视频之类的)来学习

**Comment by zhuangside** [comment]
好的，多谢老兄，我只了解python的语法但我想试着做一个，请问有哪些相关的学习资料(例如书籍，视频之类的)学习后可以做一个语音助手

**Comment by caozx1110** [comment]
> 好的，多谢老兄，我只了解python的语法但我想试着做一个，请问有哪些相关的学习资料(例如书籍，视频之类的)学习后可以做一个语音助手

我当时也没看啥书or视频，就是在baidu/google上搜索，尽量把东西拆解一下，分模块处理叭

**Comment by zhuangside** [comment]
好的，谢谢
